workspace:
    base: /src
    # path: py_selenium
    
kind: pipeline
name: default

clone:
depth: 1

steps:
- name: test
  image: python
  commands:
    - pip install -r requirements.txt
    - pyinstaller main.py

# - name: pack_init
#   image: cdrx/pyinstaller-linux:python3
#   pull: always
#   commands:
#     - pyinstaller main.py

- name: pack_linux
  image: cdrx/pyinstaller-linux:python3
  pull: always
    
- name: list
  image: alpine
  commands:
    - pwd
    - ls -al
    - cd ..
    - pwd
    - ls -al
    